### ISSUE TITLE
Object reference not set to instance of an object when using records

### ISSUE THREAD

**Issue by coeur85** [Tynamix/ObjectFiller.NET#136]
i prefer to use records when it comes data modeling, class for brokers and services.

i'm  trying to use filler with public record and it's always throws an exception.

when i switched my model to class it worked like a charm, any way i can go around this ?

**Comment by HerrLoesch** [comment]
I have an idea but could you please provide us with more information. The exception type and message would be helpful.

**Comment by essieessara** [comment]
I have the same error 
![object filler](https://user-images.githubusercontent.com/31780972/166107932-e5622294-3c37-448e-b193-ce74383577a8.png)
the repo to be checked https://github.com/essieessara/ObjectFiller.app.git

**Comment by coeur85** [comment]
> I have the same error ![object filler](https://user-images.githubusercontent.com/31780972/166107932-e5622294-3c37-448e-b193-ce74383577a8.png) the repo to be checked https://github.com/essieessara/ObjectFiller.app.git

if you changed the model type from class to record that should break things

**Comment by HerrLoesch** [comment]
Today I had a short look into the problem: Reason for this bug is, that records are immutable classes or structs. Till this point we always created an instance of a class or struct and set then its properties. Records have no setter thus the setter method we get from the framework is simply null and causes the error. This seems to make a bigger change to the filler necessary which also a bit tricky because their does not seem to be an official way of getting the information if a type is actually a record or not.

**Comment by Tynamix** [comment]
@HerrLoesch i also thought it would be hard but then i read this:
https://www.meziantou.net/csharp9-init-only-properties-are-not-read-only.htm
Seems to me like records are only code sugar at least for the reflection api. 

I changed https://github.com/Tynamix/ObjectFiller.NET/blob/40870dae6ab2cc318da63dd700409d0a8e11d080/Tynamix.ObjectFiller/NetTypeApiExtension.cs#L40 to 
```csharp
return source?.SetMethod; 
```
and it works and all unit tests are running

**Comment by HerrLoesch** [comment]
Did not expect it to set the value without a setter method :D

**Comment by Tynamix** [comment]
released https://www.nuget.org/packages/Tynamix.ObjectFiller/1.5.8 with support for records.
