### ISSUE TITLE
Do we want to remove optional parameters?

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#64]
I saw that we are using optional parameters in our public API. For example in Lipsum:

``public Lipsum(LipsumFlavor flavor, int paragraphs = 3, int minSentences = 3, int maxSentences = 8, 
160             int minWords = 10, int maxWords = 50, int? seed = null) ``

Optional parameters are compiled into the Client library. This might cause Problems if we change them, which why they shouldn't be used in public APIs. On the other hand it's annoying to replace them with overloads.

My question is now: Do we want to replace all optional parameters with overloads to stay save or do we want to keep them as they are, even with possible side effects?

**Comment by Tynamix** [comment]
Good one, should be done in the next version!

**Comment by Tynamix** [comment]
We sould do it overloaded constructors

**Comment by Tynamix** [comment]
I looked at all plugins. The Lipsum plugin was the only one with optional pramaters and i changed it. But especially there it is worth to think about if it is better to use optional parameters.. Because maybe u want to have a lipsum text with 3 paragraphs but you are not interested in how many min or max words/sentences will be generated for that. Now you have to think about that because the order of the parameter matters... What do you think about it @HerrLoesch ?

**Comment by Tynamix** [comment]
Changed Lipsum plugin to have constructors with non optional parameters. The constructor which has all parameters is left with optional parameters to be able to just set up the things which are needed.
